// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qagkfvkbpgqvmjqdhxis.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZ2tmdmticGdxdm1qcWRoeGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjA5NTMsImV4cCI6MjA2MzgzNjk1M30.2BrXy-jCvCk7yLX-ySyAwDkYGXFtZMfyZjNRzgRbc5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);